# logistic regression on binary mnist configuration 


# general settings
seed: 0
cuda: 3    # if multiple GPUs, set `CUDA_VISIBLE_DEVICES="your GPU ids"`
save: "FedAvg_binary_mnist" 


# dataset settings
dataset: "binary_mnist"
input_channel: 1
input_size: 28
num_classes: 2


# unlearning settings
unlearn_method: "FedGB"
unlearn_select: "backdoor"
target_label: 1
src_label: 0
unlearn_perc: 0.05
unlearn_client_perc: 1.0


# model settings
model: "LogisticRegression_BINARY_MNIST"
pretrain_model: null


# optimizer settings
optimizer: "SGD"
criterion: "BCEWithLogitsLoss"

lr: 0.1
ft_lr: 0.1
momentum: 0.0
weight_decay: 0.
beta1: 0.9
beta2: 0.999
clipping: 0

batch_size: 512


# federated settings
num_clients: 10
partition: "iid"
alpha: 0.5

global_epochs: 200
local_epochs: 1
unlearn_epochs: 80
refine_epochs: 20

communicator: "Communicator"
compressor: "Compressor"
k: null
sparsity: null
is_init_compressed: false